version: '3.7'
services:
  cpp:
    build: .
    working_dir: /cpp
    command: ["tail", "-f", "/dev/null"]
    volumes:
    # - cpp-native-osx-sync:/cpp:nocopy
    - .:/cpp
# volumes:
#   cpp-native-osx-sync:
#     external: true
